### ISSUE TITLE
App hangs trying to onboard an atsign that has been reset

### ISSUE THREAD

**Issue by XavierChanth** [atsign-foundation/at_widgets#74]
**Describe the bug**
Wavi tries to onboard the last used atsign, which hangs when the atsign is no longer activated.

**To Reproduce**
1. First I onboard an atsign
2. Then I reset the atsign on atsign.com
3. And then relaunch the app
4. The app is stuck loading for an unknown length of time

**Expected behavior**
An option to reset or switch the atsign to onboard.

**Screenshots**
Video of the issue:
https://drive.google.com/file/d/1fzCyWpP4ALhosptcCXf5lCzjSsoSDYWv/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: ios 14.6
 - Browser N/A
 - Version N/A

**Were you using an @‎application when the bug was found?**
  - @‎wavi

**Additional context**
The atsign was running on dess.

**Comment by DivyaYadavareddy** [comment]
In this issue I followed reproduce steps and tested app it’s working fine.
when we onboard to a primary @sign and after onboarding  I reset that @sign in atsign.com
And then I relaunch the app it is showing server unavailable or it is in loading state because we reset the primary @sign. so 
Expected behaviour is to switch to another @sign by pressing reset button it will show @sign list then we Will delete that primary reset @sign then it is working fine .below attached

https://user-images.githubusercontent.com/60208911/127438683-87ad29d0-f536-4e53-889b-d3fdc1195e1a.mov

 recording video

**Comment by XavierChanth** [comment]
Thank you Divya , now that #56 has been resolved, I am able to reset my atsigns.

I noticed in your demo when you press "Let's go!" the loader spinner duration is much shorter than on my phone,
that is the main reason I opened this issue. Sometimes I will have to wait several minutes before I can do anything in the app.

**Comment by XavierChanth** [comment]
Follow up to my comment above, in the past average time for the loading spinner was about 2-3 minutes, it is now about 1-1.5 on my iPhone. These numbers may be poor due to external factors. I don't think this issue is urgent by any means, but I do think it is important to document it.

**Comment by DivyaYadavareddy** [comment]
@XavierChanth can this issue be closed?

**Comment by xavierchanth** [comment]
Yes, I think the issue is gone, I wasn't able to reproduce it again.

**Comment by sarika01** [comment]
@DivyaYadavareddy I think the reset button shown above is in the wavi app and not on the at_onboarding_flutter widget. With the latest version 2.1.3 of the onboarding package on pub.dev, I am getting this screen with no reset button.
![Simulator Screen Shot - iPhone 8 - 2021-08-25 at 16 20 32](https://user-images.githubusercontent.com/12222326/130778630-bce6528e-ea24-48dc-9fed-2ec9eb5ad059.png)
